# Use a imagem oficial do Node.js
FROM node:14

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /usr/src/app

# Copie o arquivo package.json e package-lock.json (se existir)
COPY package*.json ./

# Instale as dependências do Node.js
RUN npm install

# Copie o restante do código-fonte
COPY . .

# Exponha a porta do Node.js (a porta que seu aplicativo Node.js está ouvindo)
EXPOSE 8080

# Comando para iniciar o aplicativo Node.js
CMD [ "node", "app.js" ]
